name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'devfolio-1.0.0/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # Step 3: Sync Website to S3
      - name: Sync Website to S3
        run: |
          aws s3 sync devfolio-1.0.0 s3://${{ secrets.AWS_S3_BUCKET }} \
            --acl public-read \
            --follow-symlinks \
            --exact-timestamps \
            --delete

      # Step 4: Invalidate CloudFront Cache
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
